<a href="https://colab.research.google.com/github/VeekshithaKulal/Data-science/blob/main/basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic numpy



In [2]:
import numpy as np

In [3]:
# Create a NumPy array from a list or tuple.
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
# Purpose: Creates range of values (start, stop, step).
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [5]:
# Purpose: Creates evenly spaced values between start & stop.

np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
# Purpose: Creates array filled with zeros.
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Purpose: Creates array filled with ones.
np.ones(5)


array([1., 1., 1., 1., 1.])

In [8]:
# Purpose: Identity matrix.
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# Purpose: Change the shape of an array without changing data.
s=np.array([1,9,5,8,3,2])
s.reshape(2, 3)


array([[1, 9, 5],
       [8, 3, 2]])

In [17]:
# Purpose: Adds all elements.
np.sum(arr)


np.int64(6)

In [18]:
# Purpose: Calculates average value.
np.mean(arr)


np.float64(2.0)

In [19]:
#  Purpose: Computes standard deviation.
np.std(arr)


np.float64(0.816496580927726)

In [23]:
# Purpose: Finds smallest or largest value.
# np.max(arr)
np.min(arr)

np.int64(1)

In [24]:
# Generates random numbers between 0 and 1.
np.random.rand(3)

array([0.74861226, 0.20664339, 0.17692775])

In [25]:
# Random integers in a specified range.
np.random.randint(1, 100)


10

In [27]:
# Combines arrays.
a=np.array([1,2,3,4])
b=np.array([6,7.8,9])
np.concatenate([a, b])


array([1. , 2. , 3. , 4. , 6. , 7.8, 9. ])

In [28]:
# Purpose: Returns unique elements.
np.unique(arr)

array([1, 2, 3])

In [29]:
# Sorts an array.
np.sort(arr)


array([1, 2, 3])

In [33]:
#  Access specific rows, columns and slices.
arr[0]
# arr[:, 1]


np.int64(1)

In [34]:
# Returns positions where condition is true.
np.where(arr > 10)

(array([], dtype=int64),)

In [38]:
# Purpose: Matrix multiplication / dot product.
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
np.dot(a, b)



np.int64(80)

In [37]:
# Purpose: Swaps rows and columns.
arr.T

array([1, 2, 3])