<a href="https://colab.research.google.com/github/VeekshithaKulal/Data-science/blob/main/Numpy_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Generate an array of 5 random integers between 10 and 50
np.random.randint(10,50,5)

array([45, 39, 22, 30, 48])

In [5]:
#  Generate a 2×3 matrix of random values between 0 and 1
np.random.rand(2,3)

array([[0.1170673 , 0.47177527, 0.66414929],
       [0.29156084, 0.63638741, 0.30983878]])

In [10]:
# Combine these two arrays into one:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate([a,b])


array([1, 2, 3, 4, 5, 6])

In [12]:
# From this array:arr = np.array([3, 7, 2, 7, 9, 2, 3])
# Find the unique values.
arr = np.array([3, 7, 2, 7, 9, 2, 3])
np.unique([arr])

array([2, 3, 7, 9])

In [17]:
# Using this matrix:Calculate its transpose.

A = np.array([[1, 2],[3, 4]])
np.transpose([A])




array([[[1],
        [3]],

       [[2],
        [4]]])

In [18]:
# Perform matrix multiplication:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [20]:
# Find the indices where elements of this array are greater than 50:
arr = np.array([12, 67, 45, 89, 23])
np.where(arr>50)

(array([1, 3]),)